version: '2'
services:
    ambassade-app:
        image: ambassade
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ambassade-mysql:3306/ambassade?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ambassade-mysql:
        extends:
            file: mysql.yml
            service: ambassade-mysql
